import json
import os

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """You are an assistant that judges whether a piece of text was written by a human or generated by an AI language model.

Judge holistic semantic and stylistic coherence: does the text contain specific, idiosyncratic, lived detail, or does it read as generically smooth, hedge-heavy, and scaffolded (for example: repetitive transitions, "in conclusion" style wrap-ups, evenly-handed phrasing with no rough edges)?

Formal, technical, academic, or dense subject-matter writing is not evidence of AI generation by itself. Academic papers, legal writing, and technical documentation are routinely written by humans in a formal register. Do not raise your AI confidence just because a text sounds formal, uses jargon, or covers an abstract topic. Instead look for the specific AI tells above (generic hedging, empty transitional scaffolding without new content, unnaturally even-handed both-sides framing regardless of the actual weight of evidence).

If you are not clearly confident either way, answer "uncertain" rather than guessing. A false accusation of AI authorship is worse than missing one, so when genuinely torn, lean toward "human" or "uncertain" rather than "ai".

Respond with ONLY a JSON object in exactly this shape, no other text:
{"verdict": "ai" | "human" | "uncertain", "llm_confidence": <number between 0.0 and 1.0>, "reasoning": "<one sentence explaining the judgment>"}"""

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def _fallback(reason):
    return {
        "verdict": "uncertain",
        "llm_confidence": 0.0,
        "reasoning": "Signal unavailable, defaulting to uncertain.",
        "error": reason,
    }


def classify_with_llm(text):
    try:
        response = _get_client().chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            response_format={"type": "json_object"},
            temperature=0.2,
        )
        raw = response.choices[0].message.content
    except Exception as exc:
        return _fallback(f"groq_api_error: {exc}")

    try:
        parsed = json.loads(raw)
        verdict = parsed["verdict"]
        llm_confidence = float(parsed["llm_confidence"])
        reasoning = str(parsed.get("reasoning", ""))
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        return _fallback(f"unparseable_response: {exc}")

    if verdict not in ("ai", "human", "uncertain"):
        return _fallback(f"invalid_verdict: {verdict}")

    llm_confidence = max(0.0, min(1.0, llm_confidence))

    return {
        "verdict": verdict,
        "llm_confidence": llm_confidence,
        "reasoning": reasoning,
    }
